### ISSUE TITLE
Order of github actions in docs compilation and sync

### ISSUE THREAD

**Issue by daquinteroflex** [flexcompute/tidy3d-faq#8]
Hi Shaung @Lius-fe ,

Hope you're well. I think I've finished integrating my changes and I think they work well. See https://github.com/flexcompute/tidy3d-faq/actions/runs/7557641561

However, I wanted to chat with you about how we wanted to manage the Github actions because there is an interdependence currently. The way I have done it now, is so that we have this repo as a "single source of truth" between the docs and web.

The way it currently works is that `sync.yaml` completes, and it triggers `compile_docs.yaml` which then commits any changes into the repo  branch (or warns if the compilation process failed for whatever reason) by a bot, and then this retriggers the sync action, but it won't commit next time as there won't be any source code repo.

The benefits of this approach are:
* sync to web does not depend on docs compilation
* We are warned if the compilation process does not work in case we need to fix it before any commit is done.

Drawbacks: 
* The sync actions runs twice

Just wanted to see if you thought this made sense or if you have any other preference of the order in which this runs?

**Comment by Lius-fe** [comment]
Hi Dario @daquinteroflex

Thanks for your feedback! I think I understand what you mean.

It seems suboptimal for the sync actions to run twice. there are two possible solutions.

1. run compile_doc.yml first, followed by sync.yml.
2. If changes in the commit involve modifications under the `_faqs` folder, trigger sync actions. Changes in other folders won't trigger the sync actions.

Given that `sync.yaml` and `compile_docs.yaml` have no dependencies, I prefer the second approach.

Pleasure discussing with you. This is my perspective. Let me know if you have any feedback. Thanks

**Comment by daquinteroflex** [comment]
Thanks for your thoughts Shaung. 

I like the second approach too. I think it means both our actions need to be updated to that _faq change trigger? I'll have a look on how to implement that exactly.
